Modifying code with echo statements and grabbing initial disk space followed by remediated disk space for further analysis by engineers when engaging with clients

diff --git a/Addigy Cache Clear b/Addigy Cache Clear
--- a/Addigy Cache Clear
+++ b/Addigy Cache Clear
@@ -1,11 +1,40 @@
-#Cleans out Addigy cached items
+#!/bin/bash
 
+# Cleans out Addigy cached items
+
+# Function to calculate disk space cleared
+calculate_space_cleared() {
+    local initial_space=$1
+    local final_space=$2
+    echo $((initial_space - final_space))
+}
+
+# Clear Addigy Library Cache
 if [ -d "/Library/Addigy/ansible/packages" ]; then
-    rm -Rf /Library/Addigy/ansible/packages/*; then
-    echo "Addigy Library Cache Cleared"
+    initial_space=$(du -s /Library/Addigy/ansible/packages | awk '{print $1}')
+    rm -Rf /Library/Addigy/ansible/packages/*
+    if [ $? -eq 0 ]; then
+        final_space=$(du -s /Library/Addigy/ansible/packages | awk '{print $1}')
+        space_cleared=$(calculate_space_cleared $initial_space $final_space)
+        echo "Addigy Library Cache Cleared. Disk space cleared: ${space_cleared}K"
+    else
+        echo "Failed to clear Addigy Library Cache."
+    fi
+else
+    echo "Addigy Library Cache directory does not exist."
 fi
 
+# Clear Addigy Download Cache
 if [ -d "/Library/Addigy/download-cache/downloaded" ]; then
-    rm -Rf /Library/Addigy/download-cache/downloaded/*; then
-    echo "Addigy Download Cache Cleared"
+    initial_space=$(du -s /Library/Addigy/download-cache/downloaded | awk '{print $1}')
+    rm -Rf /Library/Addigy/download-cache/downloaded/*
+    if [ $? -eq 0 ]; then
+        final_space=$(du -s /Library/Addigy/download-cache/downloaded | awk '{print $1}')
+        space_cleared=$(calculate_space_cleared $initial_space $final_space)
+        echo "Addigy Download Cache Cleared. Disk space cleared: ${space_cleared}K"
+    else
+        echo "Failed to clear Addigy Download Cache."
+    fi
+else
+    echo "Addigy Download Cache directory does not exist."
 fi
